### ISSUE TITLE
What does "forbidding the use of function templates" mean?

### ISSUE THREAD

**Issue by smeenai** [itanium-cxx-abi/cxx-abi#169]
Chapter 1 of https://itanium-cxx-abi.github.io/cxx-abi/abi.html says the following:

>  While this ABI has generally stood up well, there are some parts of it that are now seen as mistakes. This document includes several recommendations for platforms adopting this ABI with no need to interoperate with existing C++ object code. These recommendations appear as follows:
>> Recommendation for new platforms: consider forbidding the use of function templates on your platform so that the ABI can remove these expression-mangling rules. 

I couldn't find a specialized definition of "function template" anywhere in the document, so I assume it's being used here in the regular C++ sense, e.g. something like `template <class T> T max(T a, T b)`. What exactly would it mean for a platform to forbid their use? Banning them entirely wouldn't be workable, of course; does this just mean forbidding them from appearing at ABI boundaries?

**Comment by jensmaurer** [comment]
This is an intentionally-ridiculous example for the format of a "recommendation for new platforms" that hopefully nobody confuses with a real recommendation.

**Comment by smeenai** [comment]
Got it. I was genuinely confused by it, but I also seem to be the first person who raised this in three years, so we can just assume I'm particularly thick and leave it at that :)

**Comment by Quuxplusone** [comment]
I was also just confused by it. (I did _suspect_ it must be a joke, but it was a confusing joke anyway.)

The problem is that the surrounding text doesn't give any hint that the recommendation isn't meant to be taken seriously. It says:

> **This document includes several recommendations** for platforms adopting this ABI with no need to interoperate with existing C++ object code. **These recommendations appear as follows:**

and then there's a list of recommendations. Without further information, I read that as "Here are the recommendations we just foreshadowed in the previous sentence. There is exactly one recommendation in the list at present."

The best way to fix this would be, not necessarily to soften the joke, but to put in some indication that this is an _example_ recommendation, not a _real_ recommendation. For example, instead of saying _"These recommendations appear **as follows,**"_ you could say something like _"These recommendations are scattered throughout the text, but always appear **with the following HTML formatting** in order to stand out from their surroundings."_ Basically just get the notion of "formatting" in there somewhere.

(This is the [use–mention distinction](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction). You need to make sure the reader knows that in this particular list you're mentioning, not using — you're exhibiting the _medium_, not the _message_ — you want the reader to focus on the finger, not on the moon.)
