### ISSUE TITLE
clarify how discriminators are determined when `if constexpr` and pack expansion remove counted entities

### ISSUE THREAD

**Issue by zygoloid** [itanium-cxx-abi/cxx-abi#40]
Testcase for which GCC and Clang are ABI-incompatible:

```
template<bool B> int *f() {
  if constexpr (B) {
    return [] {
      static int n;
      return &n;
    } ();
  } else {
   return [] {
      static int n;
      return &n;
    } ();
  }
}

int *p = f<false>();
```

Clang mangles the lambda as the first lambda within `f<false>`, GCC mangles it as the second. I think Clang is correct: the lexically first lambda is discarded by the `if constexpr`.

Similar things happen with pack expansion:

```
template<typename ...T> int *f() {
  ( ([] { return 0; } () + T()), ... );
  return [] { static int n; return &n; } ();
}

int *g() {
  return f<int, char, double>();
}
```

Here, the mangling of the returned static int should depend on the number of template arguments passed to `f`. (Clang implements that; GCC acts as if the static int is within the second lambda in the instantiation.)

Presumably we should clarify the ABI to say that the discriminator is based on the (imaginary) lexical order in the *instantiation*, not the order in the template definition.

**Comment by daveedvdv** [comment]
> On Oct 12, 2017, at 5:43 PM, Richard Smith <notifications@github.com> wrote:
> 
> Testcase for which GCC and Clang are ABI-incompatible:
> 
> template<bool B> int *f() {
>   if constexpr (B) {
>     return [] {
>       static int n;
>       return &n;
>     } ();
>   } else {
>    return [] {
>       static int n;
>       return &n;
>     } ();
>   }
> }
> 
> int *p = f<false>();
> Clang mangles the lambda as the first lambda within f<false>, GCC mangles it as the second. I think Clang is correct: the lexically first lambda is discarded by the if constexpr.
> 
> Similar things happen with pack expansion:
> 
> template<typename ...T> int *f() {
>   ( ([] { return 0; } () + T()), ... );
>   return [] { static int n; return &n; } ();
> }
> 
> int *g() {
>   return f<int, char, double>();
> }
> Here, the mangling of the returned static int should depend on the number of template arguments passed to f. (Clang implements that; GCC acts as if the static int is within the second lambda in the instantiation.)
> 
> Presumably we should clarify the ABI to say that the discriminator is based on the (imaginary) lexical order in the instantiation, not the order in the template definition.
> 

Yes, that sounds right to me.

	Daveed

**Comment by zygoloid** [comment]
Added a pull request describing the rule I think we've agreed on. This matches EDG's behavior, mostly matches Clang's and is substantially different from GCC's :)

In particular, Clang only renumbers closure types in template instantiations, and inherits the numbering for everything else. I believe that is a valid approach in language as it stands today, but only because there happens to be no way to pack-expand any numbered entity other than a closure type yet. I expect that to change, so adopting EDG's rule (effectively: renumber everything during template instantiation, as if we instantiated by token replay) seems best.

**Comment by rjmccall** [comment]
Is the different treatment of `constexpr if` in templates and non-templates justifiable?

**Comment by rjmccall** [comment]
I'm also uncertain about consistently using the last token in the entity.  That rule seems to be justifiable for lambdas, but I'm not sure it's reasonable for e.g. static locals.  While static locals cannot be lexically nested in the same semantic context in standard C++, they can be lexically nested in vendor-extended C++ due to statement-expressions, and I think we might expect a naive compiler to pick a discriminator as soon as the declarator was processed rather than after processing the initializer.

**Comment by zygoloid** [comment]
> Is the different treatment of `constexpr if` in templates and non-templates justifiable?

Yes, I think so; `constexpr if` does different things in templates and non-templates.

In a non-template, it's normal code that's just not emitted (we also turn off return type deduction, but not much else). In particular, you can instantiate a template in the not-chosen branch, using a local type from the not-chosen branch, and end up needing to emit a symbol (eg, the initializer for a templated variable). So we must number things in the non-template case.

In a template, `constexpr if` fully discards the not-chosen branch: we don't even substitute into it, so there's nothing we could number even if we wanted to.

> I'm also uncertain about consistently using the last token in the entity.

I think using the token at which the identity of the entity is known (the last token in the declaration, excluding a definition / body / initializer) would be reasonable. For a lambda, that'd mean you pick the `{`, not the `}` as in the current pull request, but I think those options are equivalent anyway, as everything inside the braces can use the lambda itself as its numbering context..

**Comment by rjmccall** [comment]
> So we must number things in the non-template case.

Hmm.  This design is quite surprising to me; I understand why it's desirable for discarded sub-statements to still be well-formed, but I'm surprised they're not at least considered to be some form of unevaluated code so that its uses are never ODR-uses and we're not even tempted to actually instantiate templates, much less emit any code for them.  Seems like an unforced error.

> For a lambda, that'd mean you pick the `{`, not the `}` as in the current pull request, but I think those options are equivalent anyway, as everything inside the braces can use the lambda itself as its numbering context.

I considered that and came to the same conclusion, but you're right that it would be more consistent to use the earlier token just to underline the point.  The only reason not to would be if something about the body ever fed into the signature, but since we control this particular definition  of "signature", it's easy enough to simply commit to not doing that.
