### ISSUE TITLE
mangling for long double

### ISSUE THREAD

**Issue by segher** [itanium-cxx-abi/cxx-abi#54]
Hi!

The cxx-abi specifies `e` as the mangling for long double.  In GCC for PowerPC, we originally used
64-bit IEEE float as long double.  When later IBM extended double ("double-double") was introduced
as the preferred long double type, that was given the mangling `g` (which is demangled as `__float128`)
so that libraries can support both floating point formats at the same time.

This doesn't work all that great.  For example, demangling _Z1fg will show the wrong type (`__float128`
instead of `long double`); as another example, `break f(long double)` in GDB will not work.

Now we have a third format for long double: 128-bit IEEE float (IEC 60559 binary128).  So we need
a new mangling for that.

I'd like to propose the mangling
   `k<builtin-type>`
to stand for "`long double` implemented the same as `<builtin-type>`".  It would be demangled as just
  `long double`

(I chose `k` for no specific reason other than it is short and was available).

Comments?

**Comment by zygoloid** [comment]
As I understand it, it's intentional that `void f(__float128)` when compiled for a "double == 64-bit" target is link-compatible with a `void f(long double)` when compiled for a "double == double-double" target. If we used `g` for the former and `kg` for the latter, that wouldn't work. I expect the same to apply for binary128-format `long double`.

If we use `kg` in both cases, then we don't need the `k`; demanglers can just choose to demangle `g` as `long double` (or `long double<__float128>` or whatever string they prefer). I expect the same to apply for binary128.

**Comment by segher** [comment]
`__float128` is not an existing type on older compilers.  It is currently the binary128 type, but
it is mangled incorrectly (not just the wrong mangling; invalid mangling).

`__float128` as demangling for `long double` has never worked for us.

**Comment by segher** [comment]
We now decided to not mangle long double different from the type is stands for, i.e. `g` for `__ibm128`
and `u9__ieee128` for `__ieee128`.  So I withdraw this request.  Thanks.
